# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "HaSEO"
license = "GPL v2"
licenselink = "https://github.com/noldor/haseo-hugo-theme/blob/master/LICENSE.txt"
description = "theme for blog in Japanese"
homepage = "https://github.com/noldor/haseo-hugo-theme"
tags = ["blog", "Japanese"]
features = ["Rename Distribution Pattern"]
min_version = 0.18

[author]
  name = "TAKEKOSHI Akishige"
  homepage = "https://blog.noldor.info/"
